[build]
  command = "npm run build"
  publish = "dist"

# This rule redirects all traffic to index.html, which is required for React Router (SPA) to work correctly on Netlify.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
